Разметка + имя наставника
htmlacademy-htmlcss/2181501-sedona-35 pull request #1
Opened 2022-11-02 18:47 UTC by svetlanaerokhova

2022-11-03 09:19 UTC, pavel-nyukalo requested changes

2022-11-03 09:19 UTC, pavel-niukalo commented on index.html
> +        <a class="navigation-logo" href="index.html">
Тег открылся, но не закрылся, это вызывает валидационные ошибки. Его нужно закрыть после `img`, перед списком

2022-11-03 09:19 UTC, pavel-niukalo commented on index.html
> +            </li>
Скрытую подпись нужно положить внутрь ссылки, поскольку она описывает именно этот элемент.

Так же по [критерию](https://up.htmlacademy.ru/htmlcss/35/criteries#ALLY-02) в скрытых подписях интерактивных элементов нужно так же добавлять точку в конце

2022-11-03 09:19 UTC, pavel-niukalo commented on index.html
> +            </li>
1. Аналогично тому, что выше написал. Про избранное
2. Ссылку хочу сюда лучше вынести в отдельный `li` - это у нас уже другой элемент

2022-11-03 09:19 UTC, pavel-niukalo commented on index.html
> +      <h1 class="visually-hidden"></h1>
Нужно добавить текст, пустым не надо оставлять

2022-11-03 09:19 UTC, pavel-niukalo commented on index.html
> +      <img class="background-image" src="" alt="Фото гор Седоны.">
Название класса уже говорит за себя - у нас это будет фоновая картинка, так что из разметки ее нужно убрать

2022-11-03 09:19 UTC, pavel-niukalo commented on index.html
> +        <b class="text-field__main">Заинтересовались?</b>
Тоже стоит добавить заголовок второго уровня, можно скрытый

2022-11-03 09:19 UTC, pavel-niukalo commented on index.html
> +        <h4 class="page-footer-title">Подпишитесь на рассылку</h4>
Нарушилась иерархия заголовков, перед этим нет ни `h3`, ни `h2`. Думаю можно заменить на `h2`, либо дать скрытый заголовок второго уровня, а этот переделать на третий

2022-11-03 09:19 UTC, pavel-nyukalo commented on index.html
> +          </button>
Тут у нас на макете есть надпись и стоит ее использовать

![image](https://user-images.githubusercontent.com/52506235/199683290-35256ca9-beea-493a-9a3a-1422dc479d92.png)

```html
<button class="button newsletter-button" type="submit">
  Подписаться
</button>
```

2022-11-03 09:19 UTC, pavel-nyukalo commented on index.html
> +            <span class="visually-hidden">Vkontakte</span>
Здесь так же про вложить скрытую подпись внутрь ссылки

2022-11-03 09:19 UTC, pavel-nyukalo commented on index.html
> +      </section>
Нет закрывающего тега `</ul>`

2022-11-03 09:19 UTC, pavel-nyukalo commented on index.html
> +        <h5 class="visually-hidden">Контакты</h5>
По структуре тут тоже должен быть `h2`

2022-11-03 09:19 UTC, pavel-nyukalo commented on index.html
> +        <a class="footer-contacts-phone" href="tel:+78128121212>+7 (812) 812-12-12</a>
В атрибуте `href` нет закрывающей кавычки

![image](https://user-images.githubusercontent.com/52506235/199683747-aa6a12c0-3a8b-41de-ba26-5e623eb21658.png)

2022-11-03 09:19 UTC, pavel-nyukalo commented on catalog.html
> +          </ul>
Здесь замечания аналогичны `index.html`

2022-11-03 09:19 UTC, pavel-nyukalo commented on catalog.html
> +            <span class="visually-hidden">Главная</span>
Так же вложить

2022-11-03 09:19 UTC, pavel-nyukalo commented on catalog.html
> +            <li class="catalog-filter-item">
`li` может быть дочерним тегом только у списков, поэтому тут надо добавить `ul`

2022-11-03 09:19 UTC, pavel-nyukalo commented on catalog.html
> +          </fieldset>
Нет закрывающего `</li>`

2022-11-03 09:19 UTC, pavel-nyukalo commented on catalog.html
> +          <button class="button" type="submit">Показать</button>
Тут нам надо еще добавить одну кнопку, а текст у этой заменить

![image](https://user-images.githubusercontent.com/52506235/199684507-89b1e9a7-7cfd-49c8-beec-8d36d8b2c31c.png)

2022-11-03 09:19 UTC, pavel-nyukalo commented on catalog.html
> +        </a>
Здесь нужно добавить третий элемент

2022-11-03 09:19 UTC, pavel-nyukalo commented on catalog.html
> +    </footer>
Те же замечания, что в `index` + надо добавить соц.сети

2022-11-05 08:47 UTC, svetlanaerokhova commented on index.html
> +      <img class="background-image" src="" alt="Фото гор Седоны.">
А что именно нужно убрать?

2022-11-05 08:53 UTC, svetlanaerokhova commented on index.html
> +        <h4 class="page-footer-title">Подпишитесь на рассылку</h4>
Внутри мейн были. h1 - Седона, h2- Преимущества, h3- Названия преимуществ. Если у каждого раздела свой заголовок, может тогда переделать на h1 в футере?)

2022-11-09 12:07 UTC, pavel-nyukalo commented on index.html
> +      <img class="background-image" src="" alt="Фото гор Седоны.">
Полностью тег

2022-11-09 12:19 UTC, pavel-nyukalo commented on index.html
> +        <b class="text-field__main">Заинтересовались?</b>
Тут секции надо дать заголовок (`h2`), скрытый, поскольку критерий требует наличие заголовков в секциях

2022-11-09 12:19 UTC, pavel-nyukalo commented on index.html
> +        <h4 class="page-footer-title">Подпишитесь на рассылку</h4>
`h1` можно вынести из `main` на уровень всего сайта. `h1` по критерию у нас должен быть один на весь сайт (за исключением `article`)

![image](https://user-images.githubusercontent.com/52506235/200828608-81bb07cf-b049-403e-87fc-13411de187e0.png)

2022-11-09 12:42 UTC, pavel-nyukalo requested changes
Так же надо поправить ошибки [валидатора](https://validator.w3.org/nu/#file)

Это главная:

![image](https://user-images.githubusercontent.com/52506235/200832970-3f86cd74-0d2b-4b96-a2d1-a558df719917.png)

Это каталог:

![image](https://user-images.githubusercontent.com/52506235/200833227-05bb5afe-b4f2-4166-9d7c-65a2ffc71bbd.png)

2022-11-09 12:42 UTC, pavel-nyukalo commented on index.html
> +        <h1 class="page-footer-title">Подпишитесь на рассылку</h>
В комментариях отписался насчет `h1`, тут все же подойдет `h2`

2022-11-09 12:42 UTC, pavel-nyukalo commented on index.html
> +            </button>
`visually-hidden` у нас потом скроет и надпись "Подписаться" пользователь не увидит.

Поэтому лучше `span` убрать и просто оставить текст в кнопке

2022-11-09 12:42 UTC, pavel-nyukalo commented on index.html
> +      </section>
Отступы немного поехали (начиная с `p` на 99 строке, получается, как будто он вложен в заголовок, но это не так - он находится на одном уровне с ним)

2022-11-09 12:42 UTC, pavel-nyukalo commented on index.html
> +      <img class="sedona" src="images\sedona.svg" width="457" height="213" alt="Седона.">
Здесь лучше полностью экспортнуть картинку - не по частям

![image](https://user-images.githubusercontent.com/52506235/200831100-cc65eafc-d15b-4bf7-bf36-ca03ee93afd4.png)

2022-11-09 12:42 UTC, pavel-nyukalo commented on index.html
> +          <img class="page-header-logo" src="images\logo-sedona.svg" width="140" height="70"alt="Логотип города Седона».">
Для надежности обратные слеши лучше заменить на обычные - `/`

2022-11-09 12:42 UTC, pavel-nyukalo commented on catalog.html
> +          <button class="button" type="submit">Сбросить</button>
У сброса есть свой `type` - `reset`, нужно его задать

2022-11-09 12:42 UTC, pavel-nyukalo commented on catalog.html
> +        <img class="background-image" src="images\catalog\catalog-background.jpg" width="1200" height="412" alt="Фон каталога.">
Это мы аналогично фоном положим - отсюда надо удалить тег

2022-11-09 12:42 UTC, pavel-nyukalo commented on images/icons/search.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="44" height="64" fill="none"><path fill="#000" d="m31.5 40-3.7-3.67c1-1.3 1.7-2.98 1.7-4.87a8 8 0 0 0-8-7.96c-4.4 0-8 3.68-8 8.06a8 8 0 0 0 12.9 6.26l3.7
Иконка поиска получилась большая

![image](https://user-images.githubusercontent.com/52506235/200831935-b4805077-7712-4fae-b1b8-a1e350cc6543.png)

Нужно экспортнуть иконку 20х20

![image](https://user-images.githubusercontent.com/52506235/200832029-10291bd9-c8ea-47ff-b1e7-89eb352ae8c6.png)

2022-11-09 12:42 UTC, pavel-nyukalo commented on images/icons/view-list.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="none"><g fill="#000" clip-path="url(#a)"><path d="M18 17h-2v2h2v-2ZM32 17H20v2h12v-2ZM18 21h-2v2h2v-2ZM32 21H20v2h12v-2ZM18 25h-2v
Эту нужно по аналогии с `view-cards.svg` экспортировать - маленькую иконку

2022-11-09 12:42 UTC, pavel-nyukalo commented on images/icons/view-slideshow.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="none"><g fill="#000" clip-path="url(#a)"><path d="M32 29H16v2h16v-2ZM30 19v6H18v-6h12Zm2-2H16v10h16V17Z"/></g><rect width="46" hei
Эту так же

2022-11-10 09:23 UTC, pavel-nyukalo approved these changes

2022-11-10 09:23 UTC, merged